services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - ${PORTAINER_PORT}:8000
      - ${PORTAINER_PORT2}:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  
  # APP
  ems-api:
    container_name: backend-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-service:
        condition: service_started
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      # - ASPNETCORE_HTTPS_PORTS=443

      # Database Configuration
      - DatabaseSettings__ConnectionString=Host=postgres;Port=5432;Database=${POSTGRES_DBNAME};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
  
      # JWT Authentication
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__AccessTokenExpirationInMinutes=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
      - JwtSettings__RefreshTokenExpirationInDays=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
  
      # Cloudinary Storage
      - Cloudinary__CloudName=${CLOUDINARY_CLOUD_NAME}
      - Cloudinary__ApiKey=${CLOUDINARY_API_KEY}
      - Cloudinary__ApiSecret=${CLOUDINARY_API_SECRET}
      - Cloudinary__FolderPath=${CLOUDINARY_FOLDER_PATH}
  
      # Redis Cache Settings
      - Redis__ConnectionString=redis:6379,connectTimeout=15000,syncTimeout=15000,abortConnect=false,allowAdmin=true
      - Redis__InstanceName=${REDIS_INSTANCE_NAME}
      - Redis__DefaultExpiryTimeInMinutes=${REDIS_DEFAULT_EXPIRY_TIME}
      - Redis__EnableLogging=${REDIS_ENABLE_LOGGING}
  
      # Service URLs
      - Services__Ai__BaseUrl=${AI_BASEURL}
  
      # Logging Configuration
      - Serilog__MinimumLevel__Default=${SERILOG_MINIMUM_LEVEL_DEFAULT}
      - Serilog__WriteTo__0__Args__path=/app/log/log.txt
    volumes:
      - ./Microservices/Expense/Log:/app/log
    networks:
      - app-network
    ports:
      - "${BE_PORT}:8080"
      # - "${BE_PORT2}:443"
  
  # AI Microservice
  ai-service:
    container_name: ai-service
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Application settings
      - PROJECT_NAME=${PROJECT_NAME}
      - PROJECT_DESCRIPTION=${PROJECT_DESCRIPTION}
      - VERSION=${VERSION}
      - DEBUG_MODE=${DEBUG_MODE}
      - LOG_LEVEL=${LOG_LEVEL}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - API_V1_STR=${API_V1_STR}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  
      # LLM API Keys
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./Microservices/AI/logs:/app/logs
    networks:
      - app-network
    ports:
      - "${AI_PORT}:8000"

  # Databases
  postgres:
    container_name: postgres-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - ./deployment/postgresql/init-scripts:/docker-entrypoint-initdb.d
      - ./deployment/postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - app-network
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  # Cache
  redis:
    container_name: redis-cache
    restart: unless-stopped
    command: redis-server --appendonly yes --loglevel verbose --protected-mode no --bind 0.0.0.0
    volumes:
      - redis_data:/data
    networks:
      - app-network
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
